FROM python:3.10-slim

WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY fake_producer.py .

# Set environment variables
ENV PYTHONUNBUFFERED=1

CMD ["python", "fake_producer.py"]