version: '3.8'

services:
  spark:
    build: .
    container_name: spark-streaming
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "app.py"]
    environment:
      - PYSPARK_PYTHON=python
    depends_on:
      - spark-master

  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    ports:
      - "7077:7077"
      - "8080:8080"

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
